apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-go-web-app
  labels:
    app: x-go-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: x-go-web-app
  template:
    metadata:
      labels:
        app: x-go-web-app
    spec:
      containers:
      - name: x-go-web-app
        image: faizanalix/x-goapp:{{.Values.image.tag }}
    
        ports:
        - containerPort: 8080
