apiVersion: v1
kind: Service
metadata:
  name: x-go-web-app
  labels:
    app: x-go-web-app
spec:
  type: ClusterIP
  selector:
    app: x-go-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

